# Generated by Django 5.0.3 on 2024-03-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='reg_no',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
