# Generated by Django 5.0.3 on 2024-03-15 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_student_reg_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(unique=True)),
                ('course_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'course_info',
            },
        ),
        migrations.AlterField(
            model_name='unit_info',
            name='course',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='app.courseinfo'),
        ),
    ]
