# Generated by Django 5.0.3 on 2024-03-15 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_courseinfo_alter_unit_info_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinfo',
            name='course_id',
        ),
    ]
