# Generated by Django 5.0.3 on 2024-03-15 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_courseinfo_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_finance',
            name='date',
        ),
    ]
